name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on VM
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          cd /home/azureuser/projects/milkproject

          git pull origin main

          cd milkman-frontend
          npm install
          npm run build

          cd ../reactadmin
          npm install
          npm run build

          cd ../milkman
          source ../env/bin/activate
          pip install -r ../requirements.txt

          pm2 restart all

          EOF